apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go/release.yaml@versionStream
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 600Mi
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: next-version
          resources: {}
        - name: jx-variables
          resources: {}
        - image: gcr.io/camunda-researchanddevelopment/cd-flow:0.0.10
          name: cdf-start-pipeline
          resources: { }
          script: |
            #!/usr/bin/env sh
            source /workspace/source/.jx/variables.sh
            export CDF_SINK=http://backend.35.204.61.61.xip.io/api/events
            cdf pipeline started --type module --module cc-go-client --project zeebe-operator --id $VERSION || true
        - name: release-binary
          resources: { }
        - name: build-and-push-image
          resources: { }
        - image: gcr.io/camunda-researchanddevelopment/cd-flow:0.0.10
          name: cdf-artifact-built
          resources: { }
          script: |
            #!/usr/bin/env sh
            source /workspace/source/.jx/variables.sh
            export CDF_SINK=http://backend.35.204.61.61.xip.io/api/events
            cdf artifact built --module cc-go-client --pipelineId $VERSION --project zeebe-operator --id cc-go-client || true
        - name: chart-docs
            resources: { }
        - name: changelog
          resources: { }
        - name: release-chart
          resources: { }
        - name: upload-binaries
          resources: { }
        - image: gcr.io/camunda-researchanddevelopment/cd-flow:0.0.10
          name: cdf-artifact-released-finished
          resources: { }
          script: |
            #!/usr/bin/env sh
            source /workspace/source/.jx/variables.sh
            export CDF_SINK=http://backend.35.204.61.61.xip.io/api/events
            cdf artifact released --module cc-go-client --pipelineId $VERSION --project zeebe-operator --id cd-flow-backend
            cdf pipeline finished --type module --module cc-go-client --project zeebe-operator --id $VERSION || true
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
